In [1]:
import numpy

In [2]:
import numpy as np

## Numpy Arrary

In [3]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

In [4]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
my_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print(b)

[1 2 3 4]


In [7]:
my_array[1, 2]

7

In [8]:
my_array[1][2]

7

In [9]:
my_array.ndim #how many dimension

2

In [10]:
my_array.shape

(2, 4)

In [11]:
my_array.size

8

In [12]:
type(my_array)

numpy.ndarray

## Creating Numpy Arrays

In [13]:
a = np.ones((3, 2))

In [14]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
c = np.random.random((3,2))
c

array([[0.25675221, 0.64261254],
       [0.89061409, 0.95201411],
       [0.89852689, 0.37498927]])

In [21]:
d = np.full((2,3), 10)

In [22]:
print(d)

[[10 10 10]
 [10 10 10]]


In [23]:
e = np.empty([2, 2])

In [24]:
e

array([[1.37961302e-306, 1.05699242e-307],
       [2.22522495e-307, 6.89795984e-307]])

In [25]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
g = np.identity(2)
g

array([[1., 0.],
       [0., 1.]])

In [27]:
h = g.copy()
h

array([[1., 0.],
       [0., 1.]])